import {FlatCompat} from "@eslint/eslintrc";
import path from "node:path";
import {fileURLToPath} from "node:url";

const dir=path.dirname(fileURLToPath(import.meta.url));
const compat=new FlatCompat({baseDirectory:dir});
const config=[
  // next-env.d.ts is generated by Next.js and can contain framework-required
  // triple-slash references. It must not be linted or edited by hand.
  {ignores:[".next/**","node_modules/**","next-env.d.ts"]},
  ...compat.extends("next/core-web-vitals","next/typescript"),
];
export default config;
