export type EntitlementView={provider:string;platform:string;access:"PURCHASED"|"SUBSCRIPTION_ACCESS"|"FREE_ACCESS"|"IMPORTED"|"SELF_REPORTED"|"UNKNOWN";verification:"VERIFIED_PROVIDER"|"VERIFIED_EVIDENCE"|"IMPORTED_UNVERIFIED"|"SELF_REPORTED";status:string;firstSeen:string;lastSeen:string;evidenceStatus?:string};export type Game = {slug:string;title:string;year:number;publisher:string;developer?:string;platforms:string[];genre:string;access:"PURCHASED"|"SUBSCRIPTION_ACCESS";verified:boolean;verification?:"VERIFIED_PROVIDER"|"VERIFIED_EVIDENCE"|"IMPORTED_UNVERIFIED"|"SELF_REPORTED";accessSource?:string;accessFreshness?:string;metadataSource?:string;entitlements?:EntitlementView[];physical:"DIGITAL_ONLY"|"PHYSICAL_AVAILABLE"|"LIMITED_PHYSICAL"|"UNKNOWN"|"PARTNER_APPROVED_FUTURE";reserved?:boolean;cover:string;description:string};
export const games: Game[] = [
 {slug:"signal-below",title:"Signal Below",year:2024,publisher:"Northstar Studio",platforms:["PC"],genre:"Adventure",access:"PURCHASED",verified:true,physical:"DIGITAL_ONLY",reserved:true,cover:"linear-gradient(145deg,#163747,#42a1a4)",description:"Descend through a drowned research station and piece together the signal that brought it back online."},
 {slug:"ashfall-circuit",title:"Ashfall Circuit",year:2022,publisher:"Ember Arc",platforms:["PC","Xbox"],genre:"Racing",access:"PURCHASED",verified:true,physical:"PHYSICAL_AVAILABLE",cover:"linear-gradient(145deg,#4c1e33,#e1774f)",description:"High-speed survival racing across the last volcanic highways."},
 {slug:"the-last-cartographer",title:"The Last Cartographer",year:2025,publisher:"Quiet Giant",platforms:["PC"],genre:"Strategy",access:"PURCHASED",verified:true,physical:"DIGITAL_ONLY",cover:"linear-gradient(145deg,#22325f,#7272dc)",description:"Map an impossible archipelago whose islands move every night."},
 {slug:"fallow-moon",title:"Fallow Moon",year:2021,publisher:"Morrow Works",platforms:["PC","PS5"],genre:"RPG",access:"SUBSCRIPTION_ACCESS",verified:false,physical:"UNKNOWN",cover:"linear-gradient(145deg,#1e3d32,#c39a4d)",description:"A pastoral role-playing story set beneath a moon that has stopped moving."},
 {slug:"hollow-frequency",title:"Hollow Frequency",year:2023,publisher:"Glass Hours",platforms:["PC"],genre:"Horror",access:"PURCHASED",verified:true,physical:"DIGITAL_ONLY",cover:"linear-gradient(145deg,#20222a,#a54b52)",description:"Tune a field radio to voices broadcasting from places that no longer exist."},
 {slug:"paper-kingdoms",title:"Paper Kingdoms",year:2019,publisher:"Folded Fox",platforms:["PC","Switch"],genre:"Puzzle",access:"PURCHASED",verified:true,physical:"PHYSICAL_AVAILABLE",cover:"linear-gradient(145deg,#64453d,#d9af73)",description:"Build and unfold a tiny kingdom where every crease changes the world."}
];
