type RecordValue=Record<string,unknown>;
export type XboxMetadata={title:string;productId:string;description?:string;publisher?:string;developer?:string;releaseYear?:number;genre?:string;imageUrl?:string};
const base=()=>process.env.OPENXBL_BASE_URL||"https://xbl.io";
const key=()=>process.env.OPENXBL_API_KEY?.trim();
async function request(path:string,init?:RequestInit){const apiKey=key();if(!apiKey)throw new Error("OPENXBL_NOT_CONFIGURED");const response=await fetch(`${base()}${path}`,{...init,headers:{"content-type":"application/json","x-authorization":apiKey,...init?.headers},cache:"no-store"});if(!response.ok)throw new Error(`OPENXBL_${response.status}`);return response.json() as Promise<unknown>}
function objects(value:unknown,result:RecordValue[]=[]):RecordValue[]{if(value&&typeof value==="object"){if(!Array.isArray(value))result.push(value as RecordValue);for(const child of Object.values(value))objects(child,result)}return result}
function stringAt(row:RecordValue,names:string[]){for(const name of names){const value=row[name];if(typeof value==="string"&&value.trim())return value.trim()}return undefined}
const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]/g,"");
function parseProduct(payload:unknown,wanted:string):XboxMetadata|undefined{const target=normalize(wanted);let best:RecordValue|undefined;for(const row of objects(payload)){const title=stringAt(row,["ProductTitle","productTitle","title","Title","name","Name"]);if(title&&(normalize(title)===target||normalize(title).includes(target)||target.includes(normalize(title)))){best=row;if(normalize(title)===target)break}}if(!best)return;const title=stringAt(best,["ProductTitle","productTitle","title","Title","name","Name"])!;const productId=stringAt(best,["ProductId","productId","productID","id","Id","StoreId","storeId"]);if(!productId)return;const image=objects(best).map(row=>stringAt(row,["Uri","uri","url","Url","imageUrl","ImageUrl"])).find(value=>value&&/^https:\/\//.test(value));const release=stringAt(best,["ReleaseDate","releaseDate","OriginalReleaseDate"]);return{title,productId,description:stringAt(best,["ProductDescription","description","Description","ShortDescription"]),publisher:stringAt(best,["PublisherName","publisher","Publisher"]),developer:stringAt(best,["DeveloperName","developer","Developer"]),genre:stringAt(best,["genre","Genre"]),releaseYear:release?new Date(release).getUTCFullYear()||undefined:undefined,imageUrl:image}}
export function openXblConfigured(){return Boolean(key())}
export async function findXboxMetadata(title:string){const paths=["/api/v2/marketplace/new","/api/v2/marketplace/top-paid","/api/v2/marketplace/best-rated","/api/v2/marketplace/most-played","/api/v2/marketplace/deals"];for(const result of await Promise.allSettled(paths.map(path=>request(path)))){if(result.status==="fulfilled"){const match=parseProduct(result.value,title);if(match){const details=await request("/api/v2/marketplace/details",{method:"POST",body:JSON.stringify({products:match.productId})}).catch(()=>null);return details?{...match,...parseProduct(details,title)}:match}}}return null}
